name: Build, format, and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    env:
      YARN_ENABLE_MIRROR: 'false'
      YARN_ENABLE_GLOBAL_CACHE: 'false'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v1
        with:
          path: .yarn/cache
          key: ${{ matrix.node-version }}-yarn2-${{ hashFiles('yarn.lock') }}

      - run: yarn --immutable
      - run: yarn build
      - run: yarn test
      - run: yarn prettier --check .
